- name: Add Docker GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

- name: Install Docker CE
  become: true
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    update_cache: yes

- name: Install docker-compose & ansible
  become: true
  pip:
    name:
      - jsondiff
      - docker-compose
      - ansible

- name: Usermod docker
  become: true
  user:
    name: exorcito
    group: docker
    append: yes

- name: Ensure Docker is running
  service:
    name: docker
    state: started
  become: true
